version: "3"
services:

  influxdb:
    image: influxdb:1.7-alpine
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=bridge_monitor
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - state-monitor-influxdb:/var/lib/influxdb
      - /home/seba/basura:/basura

  kapacitor:
    image: kapacitor:1.5.3-alpine
    ports:
      - "9092:9092"
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_LOGGING_LEVEL=INFO
      - KAPACITOR_REPORTING_ENABLED=false
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_USERNAME=admin
      - KAPACITOR_INFLUXDB_PASSWORD=admin
    links:
      - influxdb
    volumes:
      - state-monitor-kapacitor-conf:/etc/kapacitor
      - state-monitor-kapacitor-data:/var/lib/kapacitor

  grafana:
    image: grafana/grafana:6.2.5
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - state-monitor-grafana:/var/lib/grafana

volumes:
  state-monitor-influxdb:
    driver: local
  state-monitor-grafana:
    driver: local
  state-monitor-kapacitor-conf:
    driver: local
  state-monitor-kapacitor-data:
    driver: local
