{
 "title": "Bridge Monitor",
 "time": { "from": "2019-07-22T15:11:29.133Z", "to": "2019-07-22T17:11:29.133Z" },
 "panels": [
  { "title": "Alert panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator lists match",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "contracts_status",
     "query": "SELECT \"validators_match\" FROM \"contracts_status\" WHERE  time > now() - 1m",
     "select": [
      [
       { "params": [ "validators_match" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validators required sig match",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "contracts_status",
     "query": "SELECT \"validators_required_signatures_match\" FROM \"contracts_status\" WHERE  time > now() - 1m",
     "select": [
      [
       { "params": [ "validators_match" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tokens balance diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts_status",
     "select": [
      [
       { "params": [ "balance_diff" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bridge contract deposits diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts_status",
     "select": [
      [
       { "params": [ "deposits_diff" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bridge contracts withdrawal diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts_status",
     "select": [
      [
       { "params": [ "withdrawal_diff" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validator balance $validator_1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "validators",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_1$/" }
     ]
    }
   ]
  },
  {
   "title": "Validator balance $validator_2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "validators",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_2$/" }
     ]
    }
   ]
  },
  {
   "title": "Validator balance $validator_3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "validators",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_3$/" }
     ]
    }
   ]
  },
  { "title": "Validators balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of available transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$validator_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "query": "SELECT mean(\"leftTx\") FROM \"validators\" WHERE (\"address\" =~ /^$validator_1$/ AND \"chain\" = 'foreign') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$validator_1$/" },
      { "condition": "AND", "key": "chain", "operator": "=", "value": "foreign" }
     ]
    },
    {
     "alias": "$validator_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "query": "SELECT mean(\"leftTx\") FROM \"validators\" WHERE (\"address\" =~ /^$validator_2$/ AND \"chain\" = 'foreign') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$validator_2$/" },
      { "condition": "AND", "key": "chain", "operator": "=", "value": "foreign" }
     ]
    },
    {
     "alias": "$validator_3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "query": "SELECT mean(\"leftTx\") FROM \"validators\" WHERE (\"address\" =~ /^$validator_3$/ AND \"chain\" = 'foreign') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$validator_3$/" },
      { "condition": "AND", "key": "chain", "operator": "=", "value": "foreign" }
     ]
    }
   ]
  },
  {
   "title": "$validator_1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "query": "SELECT mean(\"leftTx\") FROM \"validators\" WHERE (\"chain\" = 'foreign' AND \"address\" =~ /^$validator_1$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_1$/" }
     ]
    }
   ]
  },
  {
   "title": "$validator_2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_2$/" }
     ]
    }
   ]
  },
  {
   "title": "$validator_3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "validators",
     "select": [
      [
       { "params": [ "leftTx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" },
      { "condition": "AND", "key": "address", "operator": "=~", "value": "/^$validator_3$/" }
     ]
    }
   ]
  },
  {
   "title": "Tokens balance  & bridge contracts deposit/withdrawals differences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Token balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Foreign",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "foreign_erc20_balance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "home_total_supply" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Foreign",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "foreign_withdrawals" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "home_withdrawals" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deposits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Foreign",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "foreign_deposits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "contracts",
     "select": [
      [
       { "params": [ "home_deposits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Validator contracts comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Foreign validators",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "validators",
     "query": "SELECT \"address\", \"balance\" FROM \"validators\" WHERE (\"chain\" = 'foreign') AND time > now() - 1m",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" }
     ]
    }
   ]
  },
  {
   "title": "Foreing required # of sig.",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "validators_required_signatures",
     "select": [
      [
       { "params": [ "requiredSignatures" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" }
     ]
    }
   ]
  },
  {
   "title": "Home validators",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "validators",
     "query": "SELECT \"address\", \"balance\" FROM \"validators\" WHERE (\"chain\" = 'home') AND time > now() - 1m",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "foreign" }
     ]
    }
   ]
  },
  {
   "title": "Home required # of sig.",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "validators_required_signatures",
     "query": "SELECT \"requiredSignatures\" FROM \"validators_required_signatures\" WHERE (\"chain\" = 'home') AND $timeFilter AND time > now() - 1m",
     "select": [
      [
       { "params": [ "requiredSignatures" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "chain", "operator": "=", "value": "home" }
     ]
    }
   ]
  }
 ]
}